export const mockDresses = [
  {
    id: 'dress-001',
    code: 'D001',
    name: 'فستان سهرة كحلي',
    description: 'فستان سهرة أنيق مع تطريز كحلي',
    itemType: 'dress',
    category: 'سهرة',
    color: 'كحلي',
    size: 'M',
    purchasePrice: 150,
    rentalPrice: 50,
    salePrice: 200,
    depositAmount: 20,
    status: 'available',
    isForRent: true,
    isForSale: false,
    images: [],
    barcode: 'DRESS-001',
    timesRented: 3,
    notes: 'فساتين مطلوبة كثيراً',
  },
  {
    id: 'dress-002',
    code: 'D002',
    name: 'فستان زفاف كلاسيك',
    description: 'فستان زفاف بتصميم كلاسيك أنيق',
    itemType: 'dress',
    category: 'زفاف',
    color: 'أبيض',
    size: 'L',
    purchasePrice: 500,
    rentalPrice: 200,
    salePrice: 800,
    depositAmount: 100,
    status: 'available',
    isForRent: true,
    isForSale: false,
    images: [],
    barcode: 'DRESS-002',
    timesRented: 1,
  },
  {
    id: 'dress-003',
    code: 'D003',
    name: 'فستان خطوبة وردي',
    description: 'فستان خطوبة بلون وردي ناعم',
    itemType: 'dress',
    category: 'خطوبة',
    color: 'وردي',
    size: 'S',
    purchasePrice: 120,
    rentalPrice: 40,
    salePrice: 180,
    depositAmount: 15,
    status: 'rented',
    isForRent: true,
    isForSale: true,
    images: [],
    barcode: 'DRESS-003',
    timesRented: 5,
  },
  {
    id: 'item-004',
    code: 'D004',
    name: 'حقيبة سهرة فضية',
    description: 'حقيبة مناسبة لفستان السهرة والمناسبات الرسمية',
    itemType: 'bag',
    category: 'حقائب',
    color: 'فضي',
    size: 'One Size',
    purchasePrice: 35,
    rentalPrice: 10,
    salePrice: 55,
    depositAmount: 5,
    status: 'available',
    isForRent: true,
    isForSale: true,
    images: [],
    barcode: 'ITEM-004',
    timesRented: 2,
  },
  {
    id: 'item-005',
    code: 'D005',
    name: 'تاج كريستال',
    description: 'إكسسوار مناسب للزفاف والخطوبة',
    itemType: 'accessory',
    category: 'إكسسوارات',
    color: 'فضي',
    size: 'One Size',
    purchasePrice: 20,
    rentalPrice: 8,
    salePrice: 35,
    depositAmount: 0,
    status: 'available',
    isForRent: true,
    isForSale: true,
    images: [],
    barcode: 'ITEM-005',
    timesRented: 4,
    notes: 'مناسب مع موديلات الزفاف',
  },
];

export const mockCustomers = [
  {
    id: 'customer-001',
    name: 'مريم البلوشي',
    phone: '9000-0001',
    address: 'مسقط، الخوير',
    measurements: 'الطول 165 سم، المقاس M',
    status: 'trusted',
    totalReservations: 6,
    activeReservations: 1,
    totalPaid: 210,
    remainingBalance: 0,
    lastReservationDate: '2026-05-12',
    notes: 'عميلة منتظمة وتلتزم بمواعيد الإرجاع.',
  },
  {
    id: 'customer-002',
    name: 'سارة الهنائية',
    phone: '9000-0002',
    address: 'السيب، المعبيلة',
    measurements: 'الطول 158 سم، المقاس S',
    status: 'normal',
    totalReservations: 2,
    activeReservations: 0,
    totalPaid: 65,
    remainingBalance: 15,
    lastReservationDate: '2026-04-28',
  },
  {
    id: 'customer-003',
    name: 'نورة العامرية',
    phone: '9000-0003',
    address: 'بوشر، الغبرة',
    measurements: 'الطول 170 سم، المقاس L',
    status: 'warning',
    totalReservations: 4,
    activeReservations: 1,
    totalPaid: 120,
    remainingBalance: 35,
    lastReservationDate: '2026-05-16',
    notes: 'تأخرت في الإرجاع مرة واحدة.',
  },
  {
    id: 'customer-004',
    name: 'هند الشكيلية',
    phone: '9000-0004',
    address: 'نزوى، فرق',
    measurements: 'المقاس M/L',
    status: 'normal',
    totalReservations: 1,
    activeReservations: 0,
    totalPaid: 30,
    remainingBalance: 0,
    lastReservationDate: '2026-03-20',
  },
  {
    id: 'customer-005',
    name: 'ليان المقبالية',
    phone: '9000-0005',
    address: 'صحار، الطريف',
    measurements: 'الطول 162 سم، المقاس M',
    status: 'blocked',
    totalReservations: 3,
    activeReservations: 0,
    totalPaid: 80,
    remainingBalance: 50,
    lastReservationDate: '2026-02-14',
    notes: 'لا يتم قبول حجز جديد قبل تسوية الرصيد.',
  },
];

export const mockReservations = [
  {
    id: 'reservation-001',
    reservationNumber: 'RSV-001',
    customerName: 'مريم البلوشي',
    customerPhone: '9000-0001',
    dressCode: 'DR-001',
    dressName: 'فستان سهرة بنفسجي ملكي',
    pickupDate: '2026-05-19',
    returnDate: '2026-05-21',
    status: 'confirmed',
    rentalPrice: 25,
    depositAmount: 30,
    totalAmount: 55,
    paidAmount: 25,
    remainingAmount: 30,
    notes: 'استلام بعد العصر.',
  },
  {
    id: 'reservation-002',
    reservationNumber: 'RSV-002',
    customerName: 'نورة العامرية',
    customerPhone: '9000-0003',
    dressCode: 'DR-003',
    dressName: 'فستان خطوبة وردي ناعم',
    pickupDate: '2026-05-16',
    returnDate: '2026-05-18',
    status: 'overdue',
    rentalPrice: 35,
    depositAmount: 40,
    totalAmount: 75,
    paidAmount: 40,
    remainingAmount: 35,
    notes: 'تحتاج متابعة للاسترجاع.',
  },
  {
    id: 'reservation-003',
    reservationNumber: 'RSV-003',
    customerName: 'سارة الهنائية',
    customerPhone: '9000-0002',
    dressCode: 'DR-002',
    dressName: 'فستان زفاف أبيض كلاسيك',
    pickupDate: '2026-05-25',
    returnDate: '2026-05-27',
    status: 'pending',
    rentalPrice: 80,
    depositAmount: 100,
    totalAmount: 180,
    paidAmount: 0,
    remainingAmount: 180,
  },
  {
    id: 'reservation-004',
    reservationNumber: 'RSV-004',
    customerName: 'هند الشكيلية',
    customerPhone: '9000-0004',
    dressCode: 'DR-004',
    dressName: 'فستان أطفال ذهبي',
    pickupDate: '2026-05-10',
    returnDate: '2026-05-12',
    status: 'returned',
    rentalPrice: 10,
    depositAmount: 15,
    totalAmount: 25,
    paidAmount: 25,
    remainingAmount: 0,
  },
];

export const deliveryReturnMockRecords = [
  {
    id: 'dr-1',
    reservationNumber: 'RES-2026-051',
    customerName: 'سارة أحمد',
    customerPhone: '0900000001',
    dressCode: 'DR-019',
    dressName: 'فستان سهرة فضي',
    status: 'pending_delivery',
    deliveryCondition: 'جاهز للتسليم بعد الكي النهائي',
    depositAmount: 120,
    lateFee: 0,
    damageFee: 0,
    depositRefundAmount: 120,
    notes: 'التسليم اليوم الساعة 6:00 مساءً.',
  },
  {
    id: 'dr-2',
    reservationNumber: 'RES-2026-052',
    customerName: 'ريم خالد',
    customerPhone: '0900000002',
    dressCode: 'DR-025',
    dressName: 'فستان مخملي أزرق',
    deliveryDateTime: '2026-05-18T14:30:00',
    deliveryCondition: 'سليم وتم القياس النهائي',
    status: 'delivered',
    depositAmount: 150,
    lateFee: 0,
    damageFee: 0,
    depositRefundAmount: 150,
    notes: 'متوقع الاسترجاع بتاريخ 2026-05-21.',
  },
  {
    id: 'dr-3',
    reservationNumber: 'RES-2026-046',
    customerName: 'ليان مازن',
    customerPhone: '0900000003',
    dressCode: 'DR-011',
    dressName: 'فستان دانتيل عاجي',
    deliveryDateTime: '2026-05-10T12:00:00',
    deliveryCondition: 'ممتاز',
    returnDateTime: '2026-05-12T17:20:00',
    returnCondition: 'نظيف وسليم',
    status: 'returned',
    depositAmount: 100,
    lateFee: 0,
    damageFee: 0,
    depositRefundAmount: 100,
  },
  {
    id: 'dr-4',
    reservationNumber: 'RES-2026-041',
    customerName: 'نور علي',
    customerPhone: '0900000004',
    dressCode: 'DR-008',
    dressName: 'فستان وردي مطرز',
    deliveryDateTime: '2026-05-07T16:00:00',
    deliveryCondition: 'جيد جداً',
    returnDateTime: '2026-05-11T19:10:00',
    returnCondition: 'تم الاسترجاع متأخر يومين',
    status: 'late',
    depositAmount: 110,
    lateFee: 20,
    damageFee: 0,
    depositRefundAmount: 90,
    notes: 'تم إبلاغ العميلة برسوم التأخير.',
  },
  {
    id: 'dr-5',
    reservationNumber: 'RES-2026-039',
    customerName: 'هدى سمير',
    customerPhone: '0900000005',
    dressCode: 'DR-004',
    dressName: 'فستان أحمر ساتان',
    deliveryDateTime: '2026-05-05T13:45:00',
    deliveryCondition: 'ممتاز',
    returnDateTime: '2026-05-09T10:30:00',
    returnCondition: 'تمزق بسيط في الذيل',
    status: 'damaged',
    depositAmount: 130,
    lateFee: 0,
    damageFee: 35,
    depositRefundAmount: 95,
    notes: 'تحويل العنصر للصيانة قبل الإتاحة للحجز القادم.',
  },
];

export const expenseMockRecords = [
  {
    id: 'exp-1',
    expenseNumber: 'EXP-2026-0501',
    expenseDate: '2026-05-03',
    title: 'تنظيف فساتين بعد موسم الأعراس',
    category: 'laundry',
    amount: 38,
    paymentMethod: 'cash',
    relatedDressCode: 'DR-021',
    relatedDressName: 'فستان سهرة كحلي',
    notes: 'تنظيف 4 فساتين شديدة الاستخدام.',
  },
  {
    id: 'exp-2',
    expenseNumber: 'EXP-2026-0502',
    expenseDate: '2026-05-05',
    title: 'تعديل مقاس فستان دانتيل',
    category: 'tailoring',
    amount: 14,
    paymentMethod: 'card',
    relatedDressCode: 'DR-011',
    relatedDressName: 'فستان دانتيل عاجي',
  },
  {
    id: 'exp-3',
    expenseNumber: 'EXP-2026-0503',
    expenseDate: '2026-05-08',
    title: 'صيانة سحاب فستان مخملي',
    category: 'maintenance',
    amount: 9.5,
    paymentMethod: 'cash',
    relatedDressCode: 'DR-025',
    relatedDressName: 'فستان مخملي أزرق',
    notes: 'استبدال السحاب الخلفي بالكامل.',
  },
  {
    id: 'exp-4',
    expenseNumber: 'EXP-2026-0504',
    expenseDate: '2026-05-12',
    title: 'شراء فستان جديد لمجموعة الصيف',
    category: 'purchase',
    amount: 185,
    paymentMethod: 'bank_transfer',
    relatedDressCode: 'DR-031',
    relatedDressName: 'فستان شيفون زمردي',
  },
  {
    id: 'exp-5',
    expenseNumber: 'EXP-2026-0505',
    expenseDate: '2026-05-14',
    title: 'إيجار المحل - مايو 2026',
    category: 'rent',
    amount: 450,
    paymentMethod: 'bank_transfer',
    notes: 'دفعة شهرية ثابتة.',
  },
  {
    id: 'exp-6',
    expenseNumber: 'EXP-2026-0506',
    expenseDate: '2026-05-16',
    title: 'رواتب فريق المتجر',
    category: 'salary',
    amount: 620,
    paymentMethod: 'bank_transfer',
    notes: 'راتب موظفتين + مساعدة دوام جزئي.',
  },
  {
    id: 'exp-7',
    expenseNumber: 'EXP-2026-0507',
    expenseDate: '2026-05-18',
    title: 'مواد تغليف وتسليم',
    category: 'other',
    amount: 27.75,
    paymentMethod: 'other',
    notes: 'أكياس حماية وعلب إكسسوارات.',
  },
];

export const paymentMockRecords = [
  {
    id: 'pay-1',
    paymentNumber: 'PAY-2026-1001',
    reservationNumber: 'RES-2026-052',
    customerName: 'ريم خالد',
    dressCode: 'DR-025',
    dressName: 'فستان مخملي أزرق',
    paymentDate: '2026-05-18',
    type: 'deposit',
    method: 'cash',
    direction: 'income',
    amount: 150,
    reservationTotal: 320,
    notes: 'عربون تأكيد الحجز.',
  },
  {
    id: 'pay-2',
    paymentNumber: 'PAY-2026-1002',
    reservationNumber: 'RES-2026-052',
    customerName: 'ريم خالد',
    dressCode: 'DR-025',
    dressName: 'فستان مخملي أزرق',
    paymentDate: '2026-05-19',
    type: 'rental',
    method: 'card',
    direction: 'income',
    amount: 100,
    reservationTotal: 320,
    notes: 'دفعة جزئية من قيمة الإيجار.',
  },
  {
    id: 'pay-3',
    paymentNumber: 'PAY-2026-1003',
    reservationNumber: 'RES-2026-041',
    customerName: 'نور علي',
    dressCode: 'DR-008',
    dressName: 'فستان وردي مطرز',
    paymentDate: '2026-05-11',
    type: 'penalty',
    method: 'cash',
    direction: 'income',
    amount: 20,
    reservationTotal: 280,
    notes: 'رسوم تأخير يومين.',
  },
  {
    id: 'pay-4',
    paymentNumber: 'PAY-2026-1004',
    reservationNumber: 'RES-2026-039',
    customerName: 'هدى سمير',
    dressCode: 'DR-004',
    dressName: 'فستان أحمر ساتان',
    paymentDate: '2026-05-09',
    type: 'penalty',
    method: 'bank_transfer',
    direction: 'income',
    amount: 35,
    reservationTotal: 300,
    notes: 'رسوم ضرر بسبب تمزق بسيط.',
  },
  {
    id: 'pay-5',
    paymentNumber: 'PAY-2026-1005',
    reservationNumber: 'RES-2026-046',
    customerName: 'ليان مازن',
    dressCode: 'DR-011',
    dressName: 'فستان دانتيل عاجي',
    paymentDate: '2026-05-12',
    type: 'refund',
    method: 'cash',
    direction: 'refund',
    amount: 100,
    reservationTotal: 260,
    notes: 'استرجاع العربون بعد إعادة العنصر بحالة ممتازة.',
  },
  {
    id: 'pay-6',
    paymentNumber: 'PAY-2026-1006',
    reservationNumber: 'RES-2026-051',
    customerName: 'سارة أحمد',
    dressCode: 'DR-019',
    dressName: 'فستان سهرة فضي',
    paymentDate: '2026-05-19',
    type: 'adjustment',
    method: 'other',
    direction: 'income',
    amount: 10,
    reservationTotal: 340,
    notes: 'تعديل سعر لخدمة تجهيز إضافية.',
  },
  {
    id: 'pay-7',
    paymentNumber: 'PAY-2026-1007',
    reservationNumber: 'RES-2026-046',
    customerName: 'ليان مازن',
    dressCode: 'DR-011',
    dressName: 'فستان دانتيل عاجي',
    paymentDate: '2026-05-08',
    type: 'rental',
    method: 'card',
    direction: 'income',
    amount: 160,
    reservationTotal: 260,
    notes: 'تسديد قيمة الإيجار.',
  },
];
